// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_FyjE8jwPsxm7XoemKqm3xHKRhsNszlI',
    appId: '1:944161837976:web:e681f8ef1daee09b6e51ed',
    messagingSenderId: '944161837976',
    projectId: 'taroot-app',
    authDomain: 'taroot-app.firebaseapp.com',
    databaseURL: 'https://taroot-app-default-rtdb.firebaseio.com',
    storageBucket: 'taroot-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJQcd5wotLOokWAPUdAltwAq2QxJ6zW0',
    appId: '1:944161837976:android:d4e9224e564eb0996e51ed',
    messagingSenderId: '944161837976',
    projectId: 'taroot-app',
    databaseURL: 'https://taroot-app-default-rtdb.firebaseio.com',
    storageBucket: 'taroot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm82hi-htFbfzT56xaNsI-JqXR8ptWZ4c',
    appId: '1:944161837976:ios:28fdd97be932d49b6e51ed',
    messagingSenderId: '944161837976',
    projectId: 'taroot-app',
    databaseURL: 'https://taroot-app-default-rtdb.firebaseio.com',
    storageBucket: 'taroot-app.appspot.com',
    iosBundleId: 'com.propsync.inc.tarrot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm82hi-htFbfzT56xaNsI-JqXR8ptWZ4c',
    appId: '1:944161837976:ios:1d679c6124c403436e51ed',
    messagingSenderId: '944161837976',
    projectId: 'taroot-app',
    databaseURL: 'https://taroot-app-default-rtdb.firebaseio.com',
    storageBucket: 'taroot-app.appspot.com',
    iosBundleId: 'com.propsync.inc.tarrot.RunnerTests',
  );
}
